name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Identity
        run: |
          git config --global user.email "rahulrajdahal@gmail.com"
          git config --global user.name "Rahul Raj Dahal"
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm run build
      - run: npx changeset version
      - run: git add -A && git commit -m 'version packages'
      - run: npx changeset publish
        env:
          NODE_AUTH_TOEKN: ${{secrets.NPM_TOKEN}}
      - run: git push -follow-tags
